### ISSUE TITLE
macros.j2 missing?

### ISSUE THREAD

**Issue by steev** [sennav/gitlab.joat#1]
https://github.com/sennav/gitlab.joat/blob/035068f2dd6accbd18e60bf3acedf8a57ee45bfa/templates/issue.j2#L1

Tries to import it, but it doesn't exist

**Comment by sennav** [comment]
Hi, nice that you're using this, I thought I was the only user 😂. I think this should be solved if you update your version of joat, `macros.j2` is an attempt to provide some common templating functions but it isn't that useful now but anyway I introduced without realizing it wouldn't be backward compatible. Can you confirm which version are you using if I'm not wrong you can do `joat --version` or `joat --help`. You should be able to update it with `cargo update joat` depending on how you have installed it.

**Comment by steev** [comment]
`joat 0.0.5` - i'm built from git - 3050ac383; as a workaround, i just did `touch macros.j2` in the folder and that seems to mostly work :)  And I'm trying it out, can't say i've used it extensively just yet.
